### ISSUE TITLE
Settings > General

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#100]
On the ‘E-mail Address’ field, check email per client specification. This is usually found on the design brief as the admin email NOT the clients’ contact email.

![image](https://cloud.githubusercontent.com/assets/18587097/15846971/2b0715de-2cac-11e6-8d3a-106f3a07263b.png)

**Comment by napolgit** [comment]
repace with bookings@westendcharters.com.au
