### ISSUE TITLE
Home: Featured image should occupy the entire width and fully display at the bottom of the page content in 991 resolutions and below. No need to apply slanting line.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/West-End-Charters#114]
![image](https://cloud.githubusercontent.com/assets/11186313/16573564/f76c321a-42a7-11e6-87f6-965d53da9c9f.png)

**Comment by napolgit** [comment]
Change layout as per mock (refer to ipad screen) when image is cropped.

**Comment by roseliesromeo** [comment]
Do not apply slant line for the image
![image](https://cloud.githubusercontent.com/assets/11186313/16723361/1c087080-477f-11e6-848c-75a801e5d673.png)
