### ISSUE TITLE
Home - testimonials: Carousel is not working.  Navigation buttons has no use.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/West-End-Charters#117]
![image](https://cloud.githubusercontent.com/assets/11186313/16644002/328cc62a-444c-11e6-8e31-c09747928699.png)

**Comment by napolgit** [comment]
Carousel and Nevigation is working on BKK side and also Cebu dev side.

**Comment by roseliesromeo** [comment]
Able to reproduce the issue.  It occurs when the page is resized.
