### ISSUE TITLE
About Us - Size of image is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#12]
![image](https://cloud.githubusercontent.com/assets/18587097/15641869/e3a5ed26-266d-11e6-8c39-3de8f568743f.png)

**Comment by napolgit** [comment]
After  discussed with Mario. Someone change style of contact us page after update content. Ignore this for now.

**Comment by Atcharanak** [comment]
Need to be fixed.
If not, please provide a ticket mentioning the amends.
