### ISSUE TITLE
Cruises(single) - Please update layout, font style as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#16]
NOTE: Also update on Events(single) 

![image](https://cloud.githubusercontent.com/assets/18587097/15643501/f8c82dfe-2677-11e6-8d35-2f7090b97a7f.png)

**Comment by napolgit** [comment]
On gallery thumbnail must use present size. Will discussed with Mario on this.

**Comment by napolgit** [comment]
Book now button , Mario was approved.

**Comment by Atcharanak** [comment]
Please provide a ticket mentioning the amends, if not fixed.
For other piont: Font-family of text content should be "OpenSans" as per design.

![image](https://cloud.githubusercontent.com/assets/18587097/16181941/1b7212c6-36cb-11e6-8ae0-a9ef2b89f021.png)

**Comment by Atcharanak** [comment]
- Misalignment is still happen. And please increase space as per design.

![image](https://cloud.githubusercontent.com/assets/18587097/16439756/86f3983c-3de5-11e6-9b52-416dcb582636.png)
