### ISSUE TITLE
Header - "Book Now" and "Click to email" text isn’t editable at backend. As per scope, there should be ACF in Business Details.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#33]
![image](https://cloud.githubusercontent.com/assets/18587097/15664069/2e4f5066-272b-11e6-8c7a-d40faac481b4.png)

**Comment by napolgit** [comment]
Change 'Business Detials' to 'Theme option' for header labels.

**Comment by Atcharanak** [comment]
Refer https://github.com/titan-cebu/West-End-Charters/issues/34 
- 'Phone Number' text should hide when Book Now field is empty. Also check on Click to email
- Please remove ACF text in 'Business Details'

![image](https://cloud.githubusercontent.com/assets/18587097/16183310/9be0111a-36da-11e6-9046-7c6eb3f5ec69.png)
