### ISSUE TITLE
Admin – custom fields: Incorrect settings of the metaboxes.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#74]
https://knowledgebase.titanweb.com.au/implementation/advanced-custom-fields-implementation/advanced-custom-fields-options

**Comment by Atcharanak** [comment]
Issue still happen.

![image](https://cloud.githubusercontent.com/assets/18587097/16186982/d92886d4-36f7-11e6-92a5-3737f05f2ca2.png)

**Comment by napolgit** [comment]
Ignore Toggle All
