### ISSUE TITLE
Tablet - Homepage(Sail with us because... section): Text and layout is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#83]
![image](https://cloud.githubusercontent.com/assets/18587097/15774508/f2d72d32-29a6-11e6-9d62-71e113a47e3e.png)

**Comment by napolgit** [comment]
As discussed with Mario. Please ignore this.

**Comment by Atcharanak** [comment]
if not fix, Please provide a ticket mentioning the amends.
