### ISSUE TITLE
Mobile - Header and banner are not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#88]
![image](https://cloud.githubusercontent.com/assets/18587097/16214879/f14342a6-3786-11e6-819a-ee99a781305f.png)

**Comment by napolgit** [comment]
Approved by Mario. Please ignore.

**Comment by Atcharanak** [comment]
As confirmed from Jolene's email, Please fix.

**Comment by napolgit** [comment]
I agree that the banner content can be hidden on mobile devises. Also the banner image has to resize within the width of the device, meaning that no matter which device you use the full image will always be visible, which means the height of the image will be less hence why we either display less information on the banner or below the banner on mobile view. This needs to be fixed.

JOLENE ERASMUS

**Comment by Atcharanak** [comment]
Sections and elements from the desktop layouts should remain visible on the mobile layouts.
so please show social media icon on mobile layout
you can refer: http://boynes-springs.stage.titanweb.com.au/
