### ISSUE TITLE
Mobile - Homepage: the is no image in the content section.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#89]
![image](https://cloud.githubusercontent.com/assets/18587097/15811952/386f73e8-2bd9-11e6-876d-fc5ae5ee5ece.png)

**Comment by napolgit** [comment]
Approved by Mario. Please ignore.

**Comment by Atcharanak** [comment]
Sorry for this point.
At last meeting: Sections and elements from the desktop layouts should remain visible on the mobile layouts. (https://knowledgebase.titanweb.com.au/implementation/mobile-and-browsers/mobile-desktop-sections)
