### ISSUE TITLE
Mobile - Homepage: Lead-in is not correct as per design.

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#90]
![image](https://cloud.githubusercontent.com/assets/18587097/15811983/9d82a7b4-2bd9-11e6-85d9-e425d112982e.png)

**Comment by napolgit** [comment]
Present layout was approved by Mario. Please ignore.

**Comment by Atcharanak** [comment]
As confirmed from Jolene's email, Please fix.

**Comment by napolgit** [comment]
Design incorrect changing a gallery grid format into a scrolling (left and right) gallery. Website sample incorrect as well, as the elements do not fit properly within the mobile, no spacing between images and long title text can also cause problems. My suggestion and the default Bootstrap standard is that the lead-ins elements will stack underneath each other. Please fix.

JOLENE ERASMUS
