### ISSUE TITLE
Mobile - Homepage(Sail with us because... section): Content layout and from layout are nor correct as per design

### ISSUE THREAD

**Issue by Atcharanak** [titan-cebu/West-End-Charters#91]
![image](https://cloud.githubusercontent.com/assets/18587097/15812096/f7176fca-2bda-11e6-8448-2aa2c78f58e9.png)

**Comment by napolgit** [comment]
Fixed only Submit button on mobile, other was approved by Mario. Please ignore.

**Comment by Atcharanak** [comment]
Please fix for all.
If not, please provide a ticket mentioning the amends.
